type TomlValue = string | number | boolean | string[] | number[] | Record<string, string>;
export type TomlObject = Record<string, unknown>;

export function parseTomlSubset(content: string): TomlObject {
  const root: TomlObject = {};
  let current: TomlObject = root;

  for (const rawLine of content.split(/\r?\n/)) {
    const line = stripComment(rawLine).trim();
    if (!line) {
      continue;
    }

    const section = line.match(/^\[([^\]]+)\]$/);
    if (section) {
      current = root;
      for (const part of splitDottedPath(section[1])) {
        const existing = current[part];
        if (!isRecord(existing)) {
          current[part] = {};
        }
        current = current[part] as TomlObject;
      }
      continue;
    }

    const eq = line.indexOf("=");
    if (eq === -1) {
      continue;
    }
    const key = line.slice(0, eq).trim();
    current[key] = parseTomlValue(line.slice(eq + 1).trim());
  }

  return root;
}

export function stringifyTomlMcp(servers: Record<string, Record<string, unknown>>): string {
  const lines: string[] = [
    "# Generated by agentmigrate. Review secrets and permissions before use.",
    ""
  ];

  for (const [name, server] of Object.entries(servers)) {
    lines.push(`[mcp_servers.${quoteDottedPart(name)}]`);
    for (const [key, value] of Object.entries(server)) {
      if (value === undefined || key === "name") {
        continue;
      }
      lines.push(`${key} = ${formatTomlValue(value)}`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function parseTomlValue(value: string): TomlValue {
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    return value.slice(1, -1);
  }
  if (value === "true") {
    return true;
  }
  if (value === "false") {
    return false;
  }
  if (value.startsWith("[") && value.endsWith("]")) {
    const inner = value.slice(1, -1).trim();
    if (!inner) {
      return [];
    }
    return splitComma(inner).map((part) => parseTomlValue(part.trim()) as string | number) as string[] | number[];
  }
  if (value.startsWith("{") && value.endsWith("}")) {
    const out: Record<string, string> = {};
    const inner = value.slice(1, -1).trim();
    if (!inner) {
      return out;
    }
    for (const part of splitComma(inner)) {
      const eq = part.indexOf("=");
      if (eq === -1) {
        continue;
      }
      const key = part.slice(0, eq).trim();
      out[key] = String(parseTomlValue(part.slice(eq + 1).trim()));
    }
    return out;
  }
  const num = Number(value);
  if (!Number.isNaN(num)) {
    return num;
  }
  return value;
}

function formatTomlValue(value: unknown): string {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (typeof value === "boolean" || typeof value === "number") {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(formatTomlValue).join(", ")}]`;
  }
  if (isRecord(value)) {
    return `{ ${Object.entries(value).map(([key, val]) => `${key} = ${formatTomlValue(val)}`).join(", ")} }`;
  }
  return JSON.stringify(String(value ?? ""));
}

function stripComment(line: string): string {
  let quote: string | undefined;
  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];
    if ((char === '"' || char === "'") && line[i - 1] !== "\\") {
      quote = quote === char ? undefined : quote ?? char;
    }
    if (char === "#" && !quote) {
      return line.slice(0, i);
    }
  }
  return line;
}

function splitComma(input: string): string[] {
  const parts: string[] = [];
  let quote: string | undefined;
  let depth = 0;
  let start = 0;
  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];
    if ((char === '"' || char === "'") && input[i - 1] !== "\\") {
      quote = quote === char ? undefined : quote ?? char;
    } else if (!quote && (char === "[" || char === "{")) {
      depth += 1;
    } else if (!quote && (char === "]" || char === "}")) {
      depth -= 1;
    } else if (!quote && depth === 0 && char === ",") {
      parts.push(input.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(input.slice(start));
  return parts;
}

function splitDottedPath(input: string): string[] {
  return input.split(".").map((part) => part.trim().replace(/^["']|["']$/g, ""));
}

function quoteDottedPart(input: string): string {
  return /^[A-Za-z0-9_-]+$/.test(input) ? input : JSON.stringify(input);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
